import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./terms.css";

const sections = [
  ["1. Eligibility", ["You must provide accurate information when creating an account or registering for an SCA tournament.", "Where a tournament has a minimum age requirement, you must satisfy that requirement before participating. Users below the applicable legal age may be required to obtain permission from a parent or legal guardian."]],
  ["2. Accounts", ["You are responsible for:", ["Keeping your account information accurate.", "Protecting your login details.", "All activities carried out through your account.", "Informing SCA promptly if you believe your account has been compromised."], "You must not impersonate another player, create accounts for fraudulent purposes, or provide false information."]],
  ["3. Tournaments and Leagues", ["Each tournament or league may have specific rules, eligibility requirements, schedules, entry fees, prize information, and competition formats.", "By registering, you agree to comply with the rules published for that competition.", "SCA may reschedule, postpone, modify, or cancel a tournament where reasonably necessary due to technical issues, insufficient participation, security concerns, organiser requirements, or circumstances outside our reasonable control."]],
  ["4. Fair Play", ["Players must compete fairly.", "The following are prohibited:", ["Cheating or using unauthorised software.", "Match fixing.", "Exploiting bugs or technical vulnerabilities.", "Account sharing where prohibited.", "False match results.", "Harassment or abusive conduct.", "Deliberately disrupting tournaments.", "Any activity intended to create an unfair competitive advantage."], "SCA may investigate suspected violations and take appropriate action."]],
  ["5. Disqualification and Suspension", ["SCA may issue warnings, remove a player from a tournament, suspend an account, or permanently restrict access where a user seriously or repeatedly violates these Terms or tournament rules.", "Where reasonably possible, users will be informed of the reason for enforcement action."]],
  ["6. Entry Fees and Payments", ["Where a tournament requires payment, all applicable fees will be clearly displayed before registration is completed.", "Users are responsible for ensuring that payment information provided is accurate and authorised.", "Payment processing may be provided through third-party payment providers."]],
  ["7. Prizes", ["Prize details and eligibility conditions will be stated on the relevant tournament page.", "Players may be required to complete identity, payment, or eligibility verification before receiving a prize.", "SCA may withhold or cancel a prize where there is reasonable evidence of fraud, cheating, false information, or violation of tournament rules."]],
  ["8. Intellectual Property", ["The SCA name, logo, website design, graphics, tournament materials, and other original content belong to SCA or their respective licensors.", "You may not copy, reproduce, distribute, sell, or commercially exploit SCA content without permission.", "Game names, logos, artwork, and trademarks belonging to third-party publishers remain the property of their respective owners."]],
  ["9. User Content", ["Where you submit usernames, team names, profile images, comments, match information, or other content, you confirm that you have the right to provide that content.", "You must not submit unlawful, defamatory, abusive, fraudulent, or infringing content."]],
  ["10. Third-Party Services", ["SCA may contain links to third-party websites, payment providers, game publishers, social platforms, or community services.", "SCA is not responsible for the availability, security, content, or policies of third-party services."]],
  ["11. Service Availability", ["We aim to keep SCA available and reliable but cannot guarantee uninterrupted or error-free access.", "Maintenance, technical faults, network problems, game-server outages, or circumstances outside our control may temporarily affect the service."]],
  ["12. Limitation of Liability", ["To the extent permitted by applicable Nigerian law, SCA will not be liable for indirect or consequential losses arising from your use of the platform.", "Nothing in these Terms excludes rights or liabilities that cannot lawfully be excluded under Nigerian law."]],
  ["13. Changes to These Terms", ["We may update these Terms when necessary.", "Material changes will be communicated through the website or other reasonable means.", "Continued use of SCA after an update means you accept the revised Terms."]],
  ["14. Governing Law", ["These Terms are governed by the laws of the Federal Republic of Nigeria.", "Any dispute relating to these Terms shall be handled in accordance with applicable Nigerian law."]],
  ["15. Contact", ["For questions regarding these Terms, contact SCA through the contact details provided on our website."]],
];

export default function TermsPage() {
  return <div className="legal-page"><Navbar/><main><header className="legal-header"><div className="legal-container"><p className="eyebrow">Legal</p><h1>Terms of Service</h1><p className="legal-updated">Last Updated: August 2026</p><p>Welcome to Short Circuit Arena (“SCA”, “we”, “us”, or “our”). These Terms of Service govern your access to and use of the SCA website, tournaments, leagues, competitions, community features, and related services.</p><strong>By accessing or using SCA, you agree to these Terms.</strong></div></header><article className="legal-container legal-content">{sections.map(([title, content]) => <section key={title}><h2>{title}</h2>{content.map((item, index) => Array.isArray(item) ? <ul key={index}>{item.map(entry => <li key={entry}>{entry}</li>)}</ul> : <p key={index}>{item}</p>)}</section>)}</article></main><Footer/></div>;
}
