import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "../TermsPage/terms.css";

const sections = [
  ["1. Fair Competition", ["All players and teams are expected to compete honestly and fairly.", "Players must rely on their own skill, teamwork, strategy, and legitimate game mechanics.", "Any attempt to gain an unfair advantage over another participant is prohibited."]],
  ["2. Cheating", ["SCA has zero tolerance for cheating.", "Prohibited activities include:", ["Using hacks, cheats, scripts, bots, or unauthorized software.", "Using tools that provide information or abilities unavailable to other players.", "Manipulating game files or systems.", "Using unauthorized hardware or software to gain an advantage.", "Deliberately exploiting serious game bugs or vulnerabilities.", "Attempting to bypass tournament security or anti-cheat systems."], "Players suspected of cheating may be required to provide reasonable evidence necessary for an investigation."]],
  ["3. Account Sharing and Impersonation", ["Players must compete using their own registered accounts unless the specific tournament rules state otherwise.", "You must not:", ["Allow another person to compete on your behalf.", "Compete using another player's identity.", "Provide false player information.", "Register an ineligible player under another identity.", "Substitute players without approval where approval is required."]]],
  ["4. Match Fixing", ["Match fixing is strictly prohibited.", "Players and teams must not intentionally:", ["Lose a match.", "Manipulate a match result.", "Arrange predetermined results.", "Give opponents an unfair advantage.", "Cooperate with another team to manipulate tournament standings."], "Offering or accepting money, gifts, prizes, or other benefits to influence a match result is prohibited."]],
  ["5. Exploiting Bugs and Glitches", ["Players must not knowingly exploit bugs, glitches, map errors, or technical problems to gain an unfair competitive advantage.", "If a significant exploit is discovered during a competition, players should report it to SCA or the tournament administrator.", "SCA may restart, cancel, or review an affected match where necessary."]],
  ["6. Player Conduct", ["Players must treat opponents, teammates, tournament officials, organizers, and community members with respect.", "The following behaviour is prohibited:", ["Harassment.", "Threats.", "Bullying.", "Hate speech.", "Discriminatory abuse.", "Excessive verbal abuse.", "Deliberate intimidation.", "Serious unsportsmanlike conduct."], "Competitive banter is permitted where reasonable, but it must not cross into harassment or abuse."]],
  ["7. Tournament Rules", ["Each SCA tournament or league may have additional rules covering matters such as:", ["Eligible games and platforms.", "Team size.", "Player substitutions.", "Match schedules.", "Game settings.", "Map selection.", "Match reporting.", "Connection issues.", "Disconnections.", "Player eligibility.", "Required evidence or recordings."], "Participants are responsible for reviewing the applicable rules before competing."]],
  ["8. Match Results", ["Players and teams must submit accurate match results.", "Submitting false scores, manipulated screenshots, altered recordings, or other fraudulent evidence is prohibited.", "Where there is a dispute, SCA may request screenshots, recordings, match histories, or other reasonable evidence."]],
  ["9. Connection and Technical Issues", ["Players are responsible for maintaining a suitable internet connection and compatible gaming equipment.", "Where a significant technical issue affects a match, tournament administrators will determine whether the match should continue, restart, or be rescheduled according to the relevant competition rules."]],
  ["10. Reporting Violations", ["Players who believe another participant has violated this policy should report the matter through the appropriate SCA support or tournament reporting channel.", "Reports should include relevant evidence where available, such as:", ["Screenshots.", "Video recordings.", "Match information.", "Player usernames.", "Tournament details."], "Submitting deliberately false reports against another player may itself result in disciplinary action."]],
  ["11. Investigations", ["SCA may investigate suspected violations of this policy.", "During an investigation, SCA may review available match records, screenshots, recordings, tournament data, player reports, and other relevant evidence.", "Players and teams are expected to cooperate reasonably with investigations."]],
  ["12. Penalties", ["Depending on the seriousness of the violation, SCA may take one or more of the following actions:", ["Issue a warning.", "Reverse a match result.", "Award a match to the opposing player or team.", "Deduct points.", "Remove a player from a tournament.", "Disqualify a team.", "Remove tournament winnings.", "Temporarily suspend an account.", "Permanently ban a player or team from SCA competitions."], "Serious offences such as cheating, match fixing, fraud, or repeated violations may result in immediate disqualification or suspension."]],
  ["13. Prize Forfeiture", ["Players or teams found to have obtained a tournament result through cheating, fraud, match fixing, or another serious violation may lose their eligibility to receive associated prizes.", "Where a prize has not yet been distributed, SCA may withhold it while an investigation is ongoing."]],
  ["14. Appeals", ["Where a player or team believes a disciplinary decision was made incorrectly, they may submit an appeal through SCA's designated support channel.", "The appeal should clearly explain the reason for the request and provide any relevant supporting evidence.", "SCA will review valid appeals and communicate its final decision."]],
  ["15. Tournament Administrator Decisions", ["Tournament administrators are responsible for enforcing competition rules and resolving disputes.", "Their decisions must be made fairly and based on the available rules and evidence.", "SCA reserves the right to review an administrator's decision where necessary to protect the integrity of a competition."]],
  ["16. Changes to This Policy", ["SCA may update this Fair Play Policy as the platform, tournaments, games, or competitive requirements change.", "The latest version will always be published on the SCA website."]],
  ["17. Contact", ["Questions, reports, or appeals relating to fair play should be submitted through the official SCA support or contact channels provided on our website."]],
];

export default function FairPlayPolicyPage() {
  return <div className="legal-page"><Navbar/><main><header className="legal-header"><div className="legal-container"><p className="eyebrow">Competition integrity</p><h1>Fair Play Policy</h1><p className="legal-updated">Last Updated: August 2026</p><p>Short Circuit Arena (“SCA”) is committed to providing a fair, competitive, respectful, and enjoyable environment for all players and teams participating in our tournaments and leagues.</p><p>This Fair Play Policy applies to all SCA competitions, including tournaments, leagues, qualifiers, community events, and other competitive activities organized or managed by SCA.</p><strong>By participating in an SCA competition, you agree to follow this policy and any additional rules provided for the specific competition.</strong></div></header><article className="legal-container legal-content">{sections.map(([title, content]) => <section key={title}><h2>{title}</h2>{content.map((item, index) => Array.isArray(item) ? <ul key={index}>{item.map(entry => <li key={entry}>{entry}</li>)}</ul> : <p key={index}>{item}</p>)}</section>)}</article></main><Footer/></div>;
}
