import { useMemo,useState } from "react";
import { ExternalLink,Plus,Radio,Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";
import { getSocialProfile,isSafePublicUrl,saveSocialProfile,socialPlatforms } from "@/data/socialLinks";
import { SectionTitle } from "@/components/Dashboard";

export function SocialLinksDisplay({profile}){if(!profile?.showSocials)return null;const links=(profile.links||[]).filter(item=>item.public&&isSafePublicUrl(item.url));if(!links.length&&!isSafePublicUrl(profile.primaryStream))return null;return <div className="social-links-display">{isSafePublicUrl(profile.primaryStream)&&<a className="button" href={profile.primaryStream} target="_blank" rel="noreferrer"><Radio/>Watch Stream</a>}{links.map(item=><a key={`${item.platform}-${item.url}`} href={item.url} target="_blank" rel="noreferrer">{item.platform}<ExternalLink/></a>)}</div>}
export default function SocialLinksEditor(){const{user}=useAuth();const id=user?.id||user?.ign||"demo-player";const publicId=user?.ign||user?.name||id;const initial=useMemo(()=>getSocialProfile(id),[id]);const[data,setData]=useState(initial);const[error,setError]=useState("");const add=()=>setData({...data,links:[...(data.links||[]),{platform:"Twitch",url:"",public:true,order:(data.links||[]).length}]});const save=()=>{const invalid=[data.primaryStream,...data.links.map(item=>item.url)].filter(Boolean).find(value=>!isSafePublicUrl(value));if(invalid){setError("Use a complete, secure https:// URL for every configured link.");return}saveSocialProfile(id,data);saveSocialProfile(publicId,data);setError("")};return <section className="dashboard-panel dashboard-form social-links-editor"><SectionTitle title="Social & Streaming" copy="Add public channels without exposing private account details."/><label className="coach-enable"><span><strong>Show Social & Streaming Links</strong><small>When off, every link is hidden from your public profile.</small></span><input type="checkbox" checked={data.showSocials} onChange={e=>setData({...data,showSocials:e.target.checked})}/></label><label>Live Stream / Channel URL<input type="url" value={data.primaryStream||""} onChange={e=>setData({...data,primaryStream:e.target.value})} placeholder="https://twitch.tv/yourchannel"/></label><div className="social-editor-list">{data.links.map((item,index)=><div key={index}><select value={item.platform} onChange={e=>setData({...data,links:data.links.map((link,i)=>i===index?{...link,platform:e.target.value}:link)})}>{socialPlatforms.map(platform=><option key={platform}>{platform}</option>)}</select><input type="url" value={item.url} onChange={e=>setData({...data,links:data.links.map((link,i)=>i===index?{...link,url:e.target.value}:link)})} placeholder="https://"/><label><input type="checkbox" checked={item.public} onChange={e=>setData({...data,links:data.links.map((link,i)=>i===index?{...link,public:e.target.checked}:link)})}/>Public</label><button type="button" onClick={()=>setData({...data,links:data.links.filter((_,i)=>i!==index)})} aria-label={`Remove ${item.platform}`}><Trash2/></button></div>)}</div><div className="dashboard-actions"><button className="button button-secondary" type="button" onClick={add}><Plus/>Add Link</button><button className="button" type="button" onClick={save}>Save Links</button><Link className="button button-secondary" to={`/players/${publicId}`}>Preview Public Profile</Link></div>{error&&<p className="dashboard-error">{error}</p>}<SocialLinksDisplay profile={data}/></section>}

export function SocialPrivacySetting(){const{user}=useAuth();const id=user?.id||user?.ign||"demo-player";const[visible,setVisible]=useState(()=>getSocialProfile(id).showSocials);return <label><span>Show social &amp; streaming links publicly</span><input type="checkbox" checked={visible} onChange={e=>{setVisible(e.target.checked);saveSocialProfile(id,{...getSocialProfile(id),showSocials:e.target.checked})}}/></label>}
