import { BarChart3, Check, Megaphone, Users } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CompanyHero, SponsorEnquiryForm, SponsorshipCard } from "@/components/Company";
import { sponsorshipOptions } from "@/data/company";
import "../CompanyPages/company.css";

const benefits = ["Access to competitive gaming audiences","Brand exposure across tournaments and leagues","Social media visibility","Branded tournament assets","Player and community engagement","Digital content opportunities","Custom activations","Reporting and campaign insights"];
const packages = [["Community Partner",["Community-led activations","Selected digital placement","Campaign collaboration"]],["Tournament Partner",["Tournament brand placement","Competition content opportunities","Player engagement options"]],["Official Partner",["Multi-event visibility","Integrated content opportunities","Partnership reporting"]],["Title Sponsor",["Leading event association","Custom branded activation","Tailored campaign support"]]];
export default function SponsorProgramPage() { return <div className="company-page"><Navbar/><main><CompanyHero eyebrow="SCA Partnerships" title="Partner With the Future of Esports" copy="Connect your brand with competitive gamers, teams, tournaments, leagues, and the growing SCA community."><a className="button" href="#partner-enquiry">Become a Sponsor</a><a className="button button-secondary" href="mailto:partnerships@sca.gg">Contact Partnerships</a></CompanyHero><section className="company-section"><div className="company-container"><div className="company-heading"><p className="eyebrow">Ways to collaborate</p><h2>Sponsorship Opportunities</h2></div><div className="sponsorship-grid">{sponsorshipOptions.map(([title,copy]) => <SponsorshipCard key={title} title={title} copy={copy}/>)}</div></div></section><section className="company-section company-surface"><div className="company-container benefit-layout"><div className="company-heading"><p className="eyebrow">Partnership value</p><h2>Why Partner With SCA</h2><p>Build relevant experiences around competitions and communities without relying on one-size-fits-all activations.</p><div className="benefit-icons"><span><Users/>Community</span><span><Megaphone/>Visibility</span><span><BarChart3/>Insights</span></div></div><ul>{benefits.map(item => <li key={item}><Check/>{item}</li>)}</ul></div></section><section className="company-section"><div className="company-container"><div className="company-heading"><p className="eyebrow">Flexible collaboration</p><h2>Sponsorship Packages</h2><p>Package scope is tailored to the campaign. Contact us for pricing.</p></div><div className="package-grid">{packages.map(([name,items]) => <article key={name}><h3>{name}</h3><ul>{items.map(item => <li key={item}><Check/>{item}</li>)}</ul><a className="text-link" href="#partner-enquiry">Contact us for pricing</a></article>)}</div></div></section><section id="partner-enquiry" className="company-section company-surface"><div className="company-container form-layout"><div className="company-heading"><p className="eyebrow">Start a conversation</p><h2>Partner Enquiry</h2><p>Tell us about your brand, objectives, and the type of partnership you are considering.</p></div><SponsorEnquiryForm/></div></section><section className="company-final-cta"><div className="company-container"><div><p className="eyebrow">SCA partnerships</p><h2>Let’s Build Something Competitive Together</h2><p>Talk to the SCA partnerships team about sponsorship opportunities designed around your brand and objectives.</p></div><a className="button" href="#partner-enquiry">Become a Sponsor</a></div></section></main><Footer/></div>; }
