import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "../TermsPage/terms.css";

const sections = [
  ["1. Information We Collect", ["Depending on how you use SCA, we may collect:", ["Name.", "Email address.", "Phone number.", "Username or gamer tag.", "Team or clan information.", "Game account information.", "Tournament registration information.", "Payment and transaction information.", "Prize payment information.", "Profile information.", "Communications with SCA.", "Device, browser, IP address, and usage information."], "We only collect information that is reasonably necessary for operating the platform and providing our services."]],
  ["2. How We Use Your Information", ["We may use personal information to:", ["Create and manage accounts.", "Register players and teams for tournaments.", "Manage tournaments and leagues.", "Process payments.", "Verify player eligibility.", "Distribute prizes.", "Provide customer support.", "Send tournament and service notifications.", "Prevent fraud and cheating.", "Maintain platform security.", "Improve the SCA website and services.", "Meet legal and regulatory obligations."]]],
  ["3. Legal Basis for Processing", ["Where required by law, we process personal data on an appropriate lawful basis, including:", ["Your consent.", "Performance of a contract with you.", "Compliance with legal obligations.", "Legitimate interests relating to operating and securing SCA."]]],
  ["4. Payments", ["Payment information may be processed by third-party payment service providers.", "SCA may not directly store full payment card or banking credentials where those details are processed securely by the relevant payment provider."]],
  ["5. Sharing Your Information", ["We may share necessary information with:", ["Payment providers.", "Tournament organisers.", "Technology and hosting providers.", "Professional advisers.", "Regulatory or law-enforcement authorities where legally required."], "We do not sell personal information."]],
  ["6. Data Security", ["We use reasonable technical and organisational measures to protect personal information against unauthorised access, loss, alteration, misuse, or disclosure.", "However, no online system can guarantee absolute security."]],
  ["7. Data Retention", ["We retain personal information only for as long as reasonably necessary for the purpose for which it was collected, including legal, accounting, security, and dispute-resolution requirements."]],
  ["8. Your Rights", ["Subject to applicable Nigerian data protection law, you may have rights relating to your personal information, including the right to:", ["Request access to your personal data.", "Request correction of inaccurate information.", "Request deletion in appropriate circumstances.", "Object to or restrict certain processing.", "Withdraw consent where processing is based on consent.", "Make a complaint regarding the handling of your personal information."]]],
  ["9. Cookies", ["SCA may use cookies and similar technologies to operate the website, remember user preferences, understand website usage, and improve performance.", "Where required, users will be provided with appropriate cookie controls."]],
  ["10. Children's Privacy", ["SCA does not knowingly collect personal information from children in circumstances where parental or guardian consent is legally required without obtaining the appropriate permission.", "Tournament-specific age requirements may also apply."]],
  ["11. Third-Party Links", ["Our website may contain links to third-party websites and services.", "Their privacy practices are governed by their own privacy policies."]],
  ["12. Changes to This Policy", ["We may update this Privacy Policy where our services or legal obligations change.", "The updated date will be displayed at the top of this page."]],
  ["13. Contact", ["For privacy enquiries or requests concerning your personal information, contact SCA using the contact details provided on our website."]],
];

export default function PrivacyPage() {
  return <div className="legal-page"><Navbar/><main><header className="legal-header"><div className="legal-container"><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p className="legal-updated">Last Updated: August 2026</p><p>Short Circuit Arena (“SCA”, “we”, “us”, or “our”) respects your privacy and is committed to handling personal information responsibly.</p><p>This Privacy Policy explains how we collect, use, store, and protect information when you use our website, tournaments, leagues, and related services.</p><strong>Our handling of personal data is intended to comply with the Nigeria Data Protection Act 2023 and other applicable Nigerian data protection requirements.</strong></div></header><article className="legal-container legal-content">{sections.map(([title, content]) => <section key={title}><h2>{title}</h2>{content.map((item, index) => Array.isArray(item) ? <ul key={index}>{item.map(entry => <li key={entry}>{entry}</li>)}</ul> : <p key={index}>{item}</p>)}</section>)}</article></main><Footer/></div>;
}
