import { useEffect,useState } from "react";
import { Plus,UserRoundCheck,X } from "lucide-react";
import { Link } from "react-router-dom";
import { coachingRoles,getCoachingProfiles,sendCoachInvitation } from "@/data/coaching";
import { addNotification } from "@/data/recruitment";
import { EmptyState,SectionTitle,StatusBadge } from "@/components/Dashboard";
import { api } from "@/lib/api";


export default function TeamCoachingStaff({teamId}){const[loaded,setLoaded]=useState(null);
  useEffect(()=>{let active=true;api.get(`/teams/${teamId}`).then(({team})=>active&&setLoaded({...team,staff:[]})).catch(()=>{});return()=>{active=false}},[teamId]);
  const team=loaded||{id:teamId,name:"",game:"",currentRole:"",staff:[]};
  const[open,setOpen]=useState(false);const[query,setQuery]=useState("");const[selected,setSelected]=useState(null);const[role,setRole]=useState("Head Coach");const[message,setMessage]=useState("");const canManage=["Owner","Captain","Manager"].includes(team.currentRole);const coaches=getCoachingProfiles().filter(item=>item.enabled&&(!query||`${item.displayName} ${item.ign}`.toLowerCase().includes(query.toLowerCase())));const invite=()=>{if(!selected)return;sendCoachInvitation({coachId:selected.userId,coachSlug:selected.slug,teamId:team.id,teamName:team.name,game:team.game,role,message});addNotification(selected.userId||selected.slug,`${team.name} invited you to join as ${role}.`);setOpen(false)};if(!loaded)return null;return <section className="dashboard-panel"><SectionTitle title="Coaching Staff" copy="Coaches, analysts, and managers are kept separate from the player roster."/>{team.staff?.length?<div className="coaching-staff-grid">{team.staff.map(person=><article key={person.id||person.name}><span>{(person.name||"C")[0]}</span><div><Link to={`/players/${person.slug||person.name}`}>{person.name}</Link><small>{person.role} · Joined {person.joinDate||"—"}</small></div></article>)}</div>:<EmptyState icon={UserRoundCheck} title="No coaching staff yet" copy="Invite an SCA coach when your team is ready."/>}{canManage&&<button className="button button-secondary" type="button" onClick={()=>setOpen(true)}><Plus/>Add Coach</button>}{open&&<div className="dashboard-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="dashboard-modal" role="dialog" aria-modal="true" aria-labelledby="add-coach-title"><button className="dashboard-modal-close" onClick={()=>setOpen(false)} aria-label="Close"><X/></button><h2 id="add-coach-title">Add Coach</h2><p>Search approved coaching profiles and send an invitation.</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search coach name or IGN"/><div className="coach-search-results">{coaches.map(coach=><button className={selected?.id===coach.id?"is-selected":""} type="button" key={coach.id} onClick={()=>setSelected(coach)}><span>{(coach.displayName||coach.ign)[0]}</span><strong>{coach.displayName||coach.ign}</strong><small>{coach.roles.join(", ")} · {coach.status}</small></button>)}</div><label>Coaching role<select value={role} onChange={e=>setRole(e.target.value)}>{coachingRoles.map(item=><option key={item}>{item}</option>)}</select></label><label>Message<textarea rows="3" value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="button" disabled={!selected} onClick={invite}>Send Coaching Invitation</button></div></div>}</section>}
