import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, CreditCard, ShieldCheck, Users } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useAuth } from "@/context/AuthContext";
import { recordPayment } from "@/data/refunds";
import "../TournamentJoinPage/tournament-join.css";

const leagueOptions={
  "path-of-legends":{id:"path-of-legends",name:"Path of Legends",game:"EA FC",season:"Season 3",status:"Registration",fee:10000,currency:"NGN",starts:"05 Sep 2026"},
  "clan-sense":{id:"clan-sense",name:"Clan Sense",game:"PUBG Mobile",season:"Season 2",status:"Registration",fee:0,currency:"NGN",starts:"05 Sep 2026"},
};
const fallbackTeam={id:"demo-unizik-sug",name:"UNIZIK SUG",game:"EA FC",currentRole:"Captain",members:[{name:"MightyNess",role:"Captain"},{name:"VON.exe",role:"Player"}]};
const money=new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0});
const readTeams=()=>{try{return JSON.parse(localStorage.getItem("sca-teams")||"[]")}catch{return[]}};

export default function LeagueJoinPage(){
  const{user}=useAuth();const[searchParams]=useSearchParams();const league=leagueOptions[searchParams.get("league")]||leagueOptions["path-of-legends"];
  const teams=useMemo(()=>{const saved=readTeams().filter(item=>["Captain","Manager"].includes(item.currentRole));return saved.length?saved:[fallbackTeam]},[]);const[teamId,setTeamId]=useState(teams[0]?.id||"");const team=teams.find(item=>item.id===teamId);
  const[form,setForm]=useState({captain:user?.ign||user?.name||team?.members?.find(member=>member.role==="Captain")?.name||"",email:user?.email||"",agreement:false});const[submitted,setSubmitted]=useState(false);const[paymentReference,setPaymentReference]=useState("");const[paymentError,setPaymentError]=useState("");const[paying,setPaying]=useState(false);const paid=league.fee>0;const canRegister=league.status==="Registration";
  useEffect(()=>{if(!paid||document.querySelector('script[data-paystack-inline]'))return;const script=document.createElement("script");script.src="https://js.paystack.co/v2/inline.js";script.async=true;script.dataset.paystackInline="true";document.head.appendChild(script)},[paid]);
  const update=e=>setForm(current=>({...current,[e.target.name]:e.target.type==="checkbox"?e.target.checked:e.target.value}));const complete=reference=>{if(reference)recordPayment({ownerId:user?.id||user?.ign||user?.email||"demo",serviceType:"League",serviceId:league.id,serviceName:`${league.name} · ${league.season}`,amount:league.fee,currency:league.currency,reference});setPaymentReference(reference||"FREE");setSubmitted(true);setPaying(false)};
  const submit=e=>{e.preventDefault();setPaymentError("");if(!canRegister){setPaymentError("Team registration is not open for this league.");return}if(!team){setPaymentError("Select a team to register.");return}if(!paid){complete();return}const key=import.meta.env.VITE_PAYSTACK_PUBLIC_KEY;if(!key){setPaymentError("Paystack is not configured yet. Add VITE_PAYSTACK_PUBLIC_KEY to enable payment.");return}if(!window.Paystack){setPaymentError("The secure payment window is still loading. Please try again.");return}setPaying(true);new window.Paystack().newTransaction({key,email:form.email,amount:league.fee*100,currency:league.currency,reference:`SCA-LEAGUE-${league.id}-${Date.now()}`,metadata:{leagueId:league.id,teamId:team.id,teamName:team.name,captain:form.captain},onSuccess:transaction=>complete(transaction.reference),onCancel:()=>setPaying(false),onError:error=>{setPaying(false);setPaymentError(error?.message||"Payment could not be completed.")}})};
  return <div className="tournament-join-page"><Navbar/><main><div className="tournament-join-container"><Link className="tournament-join-back" to={`/leaguespage/leaguepageoverview?league=${league.id}`}><ArrowLeft/>Back to league</Link><div className="tournament-join-layout"><header><p className="eyebrow">Team league registration</p><h1>Enter your team.</h1><p>Confirm the roster representing your team in {league.name}.</p><div className="join-tournament-summary"><span className={paid?"paid-entry":"free-entry"}>{paid?`${money.format(league.fee)} team entry`:"Free team entry"}</span><span>{league.game} · {league.season}</span><span>Starts {league.starts}</span></div></header><section className="tournament-join-card">{submitted?<div className="join-success"><CheckCircle2/><p className="eyebrow">Team registration received</p><h2>{team.name} is registered.</h2>{paid&&<p className="payment-reference">Payment reference: <strong>{paymentReference}</strong></p>}<p>League updates, fixtures, and approval status will appear on the team dashboard.</p><Link className="button" to="/dashboard/leagues">View my leagues</Link></div>:<><div className="join-form-heading"><ShieldCheck/><div><h2>Team entry form</h2><p>{paid?"Confirm your team, then pay securely with Paystack.":"This league is free to enter. Confirm your roster to register."}</p></div></div><form onSubmit={submit}><label>Select team<select value={teamId} onChange={event=>setTeamId(event.target.value)} required>{teams.map(item=><option value={item.id} key={item.id}>{item.name} · {item.game}</option>)}</select></label><label>Captain / Manager IGN<input name="captain" value={form.captain} onChange={update} required/></label><label>Contact email<input name="email" type="email" value={form.email} onChange={update} placeholder="captain@example.com" required/></label><div className="join-payment-summary"><div><span>Confirmed roster</span><strong>{team?.members?.length||0} players</strong></div><p><Users/>{team?.members?.map(member=>member.name).join(", ")||"Add players from the team dashboard"}</p></div>{paid&&<div className="join-payment-summary"><div><span>Team entry fee</span><strong>{money.format(league.fee)}</strong></div><p><CreditCard/>Secure payment powered by Paystack</p></div>}<label className="join-consent"><input name="agreement" type="checkbox" checked={form.agreement} onChange={update} required/><span>I am authorized to register this team and confirm that its roster agrees to the league rules, Refund Policy, and Fair Play Policy.</span></label>{paymentError&&<p className="join-payment-error" role="alert">{paymentError}</p>}<button className="button" type="submit" disabled={paying}>{paid?<><CreditCard/>{paying?"Opening Paystack…":`Pay ${money.format(league.fee)} & register team`}</>:"Complete free team registration"}</button></form></>}</section></div></div></main><Footer/></div>;
}
