import { CalendarDays, Check, ShieldCheck, Trophy, Users } from "lucide-react";
import { Link } from "react-router-dom";
import LeaguesNav from "../Navbar/LeaguesNav";
import { leagueTeams } from "@/data/leagueTeams";
import "./league-detail.css";

export default function LeagueOverview() {
  return <main className="league-detail"><div className="league-detail-container"><LeaguesNav/><header className="league-header"><div><p className="eyebrow">Path of Legends · Season 3</p><h1>League overview</h1><p>A season-long team competition where eight rosters play weekly fixtures before the top four advance to the championship playoffs.</p></div><button className="button" type="button">Register a team</button></header><section className="league-facts">{[[CalendarDays,"12 weeks","Season length"],[Users,"8 teams","League field"],[Trophy,"₦2.5M","Prize pool"],[ShieldCheck,"Top 4","Playoff places"]].map(([Icon,value,label]) => <div key={label}><Icon/><strong>{value}</strong><span>{label}</span></div>)}</section><div className="league-overview-grid"><section className="league-panel"><p className="eyebrow">Competition format</p><h2>How the season works</h2><ul className="league-check-list"><li><Check/>Each team plays every other team twice during the regular season.</li><li><Check/>Teams earn three points for a win and one point for a draw.</li><li><Check/>The top four teams qualify for the championship playoffs.</li><li><Check/>Eligible substitutes may be used within the published roster rules.</li></ul></section><section className="league-panel season-dates"><p className="eyebrow">Key dates</p><h2>Season timeline</h2><div><span>Registration closes</span><strong>28 August 2026</strong></div><div><span>Regular season</span><strong>05 Sep – 21 Nov</strong></div><div><span>Playoffs</span><strong>28 November 2026</strong></div><div><span>Grand final</span><strong>05 December 2026</strong></div></section></div><section className="league-teams-section"><div className="league-section-heading"><div><p className="eyebrow">Confirmed rosters</p><h2>Competing teams</h2></div><span>8 teams</span></div><div className="league-team-grid">{leagueTeams.map(team => <Link className="league-team-card" key={team.slug} to={`/teams/${team.slug}`} aria-label={`View ${team.name} team profile`}><img src={team.logo} alt=""/><div><strong>{team.name}</strong><span>Confirmed roster · View team</span></div></Link>)}</div></section></div></main>;
}
