import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, CreditCard, ShieldCheck } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import Navbar from "@/components/Navbar"; import Footer from "@/components/Footer"; import { useAuth } from "@/context/AuthContext";
import "./tournament-join.css";

const tournamentOptions={
  "warzone-hyperx-2026":{id:"warzone-hyperx-2026",name:"Call of Duty: Warzone by HyperX",game:"Warzone",status:"Upcoming",fee:2500,currency:"NGN",format:"Solo · Battle Royale TPP",starts:"22 Dec · 21:00 WAT"},
  "sca-mobile-masters":{id:"sca-mobile-masters",name:"SCA Mobile Masters",game:"PUBG Mobile",status:"Upcoming",fee:0,currency:"NGN",format:"Squads · Mobile",starts:"15 Aug · 18:00 WAT"},
  "pubg-red-bull":{id:"pubg-red-bull",name:"PUBG Tournament by Red Bull",game:"PUBG",status:"Upcoming",fee:1500,currency:"NGN",format:"Squads · Battle Royale",starts:"26 Sep · 18:00 WAT"},
};
const money=new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0});

export default function TournamentJoinPage(){
  const[searchParams]=useSearchParams();const tournament=tournamentOptions[searchParams.get("tournament")]||tournamentOptions["warzone-hyperx-2026"];
  const{user}=useAuth();const[submitted,setSubmitted]=useState(false);const[paymentReference,setPaymentReference]=useState("");const[paymentError,setPaymentError]=useState("");const[paying,setPaying]=useState(false);const[form,setForm]=useState({ign:user?.ign||user?.name||"",email:user?.email||"",gameId:"",platform:"PC",team:"",agreement:false});
  const paid=tournament.fee>0;const canRegister=tournament.status==="Upcoming"; const update=e=>setForm(current=>({...current,[e.target.name]:e.target.type==="checkbox"?e.target.checked:e.target.value}));
  useEffect(()=>{if(!paid||document.querySelector('script[data-paystack-inline]'))return;const script=document.createElement("script");script.src="https://js.paystack.co/v2/inline.js";script.async=true;script.dataset.paystackInline="true";document.head.appendChild(script)},[paid]);
  const completeRegistration=reference=>{setPaymentReference(reference||"FREE");setSubmitted(true);setPaying(false)};
  const submit=e=>{e.preventDefault();setPaymentError("");if(!canRegister){setPaymentError("Registration is not available for this tournament.");return}if(!paid){completeRegistration();return}const key=import.meta.env.VITE_PAYSTACK_PUBLIC_KEY;if(!key){setPaymentError("Paystack is not configured yet. Add VITE_PAYSTACK_PUBLIC_KEY to enable payment.");return}if(!window.Paystack){setPaymentError("The secure payment window is still loading. Please try again.");return}setPaying(true);const paystack=new window.Paystack();paystack.newTransaction({key,email:form.email,amount:tournament.fee*100,currency:tournament.currency,reference:`SCA-${tournament.id}-${Date.now()}`,metadata:{tournamentId:tournament.id,playerIgn:form.ign,gameId:form.gameId},onSuccess:transaction=>completeRegistration(transaction.reference),onCancel:()=>setPaying(false),onError:error=>{setPaying(false);setPaymentError(error?.message||"Payment could not be completed.")}})};
  return <div className="tournament-join-page"><Navbar/><main><div className="tournament-join-container"><Link className="tournament-join-back" to={`/tournamentspage/overview?tournament=${tournament.id}`}><ArrowLeft/>Back to tournament</Link><div className="tournament-join-layout"><header><p className="eyebrow">Tournament registration</p><h1>Join the arena.</h1><p>Confirm your player details to enter {tournament.name}.</p><div className="join-tournament-summary"><span className={paid?"paid-entry":"free-entry"}>{paid?`${money.format(tournament.fee)} entry fee`:"Free entry"}</span><span>{tournament.format}</span><span>Starts {tournament.starts}</span></div></header><section className="tournament-join-card">{submitted?<div className="join-success"><CheckCircle2/><p className="eyebrow">Registration received</p><h2>You’re registered.</h2>{paid&&<p className="payment-reference">Payment reference: <strong>{paymentReference}</strong></p>}<p>Your entry has been saved. Check your dashboard for tournament and check-in updates.</p><Link className="button" to="/dashboard/tournaments">View my tournaments</Link></div>:<><div className="join-form-heading"><ShieldCheck/><div><h2>Player entry form</h2><p>{paid?"Complete your details, then pay securely with Paystack.":"This tournament is free to enter. Confirm your in-game details to register."}</p></div></div><form onSubmit={submit}><label>IGN / Gamer Tag<input name="ign" value={form.ign} onChange={update} required/></label><label>Email address<input name="email" type="email" value={form.email} onChange={update} placeholder="you@example.com" required/></label><label>{tournament.game} player ID<input name="gameId" value={form.gameId} onChange={update} placeholder="Enter your player ID" required/></label><label>Platform<select name="platform" value={form.platform} onChange={update}><option>PC</option><option>PlayStation</option><option>Xbox</option><option>Mobile</option></select></label><label>Team name <small>(optional)</small><input name="team" value={form.team} onChange={update} placeholder="Solo players can leave this blank"/></label>{paid&&<div className="join-payment-summary"><div><span>Entry fee</span><strong>{money.format(tournament.fee)}</strong></div><p><CreditCard/>Secure payment powered by Paystack</p></div>}<label className="join-consent"><input name="agreement" type="checkbox" checked={form.agreement} onChange={update} required/><span>I confirm that my details are correct and agree to the tournament rules, Refund Policy, and Fair Play Policy.</span></label>{paymentError&&<p className="join-payment-error" role="alert">{paymentError}</p>}<button className="button" type="submit" disabled={paying}>{paid?<><CreditCard/>{paying?"Opening Paystack…":`Pay ${money.format(tournament.fee)} & register`}</>:"Complete free registration"}</button></form></>}</section></div></div></main><Footer/></div>}
