import { useMemo,useState } from "react";
import { Archive,Copy,Edit3,Plus,Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";
import { EmptyState,SectionTitle,StatusBadge } from "@/components/Dashboard";
import { deleteLoadout,getAuthorLoadouts,getVoteSummary,saveLoadout } from "@/data/loadouts";
import "@/pages/LoadoutsPage/loadouts.css";

const tabs=["Published","Drafts","Archived"];
export default function DashboardLoadouts(){const{user}=useAuth();const identity=user?.id||user?.ign||user?.name;const[tab,setTab]=useState("Published");const[version,setVersion]=useState(0);const items=useMemo(()=>getAuthorLoadouts(identity),[identity,version]);const status=tab==="Drafts"?"Draft":tab.slice(0,-1);const visible=items.filter(item=>item.status===status);const totals=items.reduce((result,item)=>{const votes=getVoteSummary(item.id);result.up+=votes.up;result.down+=votes.down;return result},{up:0,down:0});const update=(item,next)=>{saveLoadout({...item,...next});setVersion(value=>value+1)};const remove=item=>window.confirm(`Delete “${item.title}”? This cannot be undone.`)&&(deleteLoadout(item.id),setVersion(value=>value+1));return <div className="dashboard-stack dashboard-loadouts"><section className="dashboard-panel"><SectionTitle title="My Loadouts" copy="Manage your published builds, private drafts, and archived strategies."/><div className="loadout-dashboard-stats">{[[items.length,"Total loadouts"],[totals.up,"Total upvotes"],[totals.down,"Total downvotes"],[items.filter(item=>item.status==="Published").length,"Published"]].map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><Link className="button button-small" to="/dashboard/loadouts/create"><Plus/>Create Loadout</Link></section><section className="dashboard-panel"><nav className="loadout-tabs" aria-label="Loadout status">{tabs.map(item=><button className={tab===item?"is-active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav>{visible.length?<div className="dashboard-loadout-list">{visible.map(item=>{const votes=getVoteSummary(item.id);return <article key={item.id}><img src={item.images?.[0]||"/assets/games/call_of_duty.png"} alt=""/><div><StatusBadge tone={item.status==="Published"?"accent":"neutral"}>{item.status}</StatusBadge><h3>{item.title}</h3><p>{item.game} · {item.loadoutType}</p><span>▲ {votes.up} &nbsp; ▼ {votes.down} · {new Date(item.createdAt).toLocaleDateString("en-NG")}</span></div><div className="dashboard-loadout-actions"><Link to={`/dashboard/loadouts/${item.id}/edit`} aria-label="Edit loadout"><Edit3/></Link>{item.status==="Published"&&<Link to={`/loadouts/${item.slug}`}>View Public Page</Link>}<button onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/loadouts/${item.slug}`)}><Copy/>Copy Link</button>{item.status==="Draft"&&<button onClick={()=>update(item,{status:"Published"})}>Publish</button>}{item.status==="Published"&&<button onClick={()=>update(item,{status:"Draft"})}>Unpublish</button>}<button onClick={()=>update(item,{status:"Archived"})}><Archive/>Archive</button><button className="is-danger" onClick={()=>remove(item)}><Trash2/>Delete</button></div></article>})}</div>:<EmptyState title="No Loadouts Yet" copy="Share your first build or strategy with the SCA community." action="Create Loadout" to="/dashboard/loadouts/create"/>}</section></div>}
