/* eslint-disable no-unused-vars */
import { Bell, ChevronRight, Gamepad2, Gift, History, LayoutDashboard, Menu, Settings, Shield, Swords, Trophy, UserRound, Users, X } from "lucide-react";
import { NavLink, Link } from "react-router-dom";

export const dashboardNav = [[LayoutDashboard,"Overview","/dashboard"],[UserRound,"My Profile","/dashboard/profile"],[Users,"My Teams","/dashboard/teams"],[Trophy,"Tournaments","/dashboard/tournaments"],[Shield,"Leagues","/dashboard/leagues"],[History,"Match History","/dashboard/matches"],[Gift,"Rewards","/dashboard/rewards"],[Bell,"Notifications","/dashboard/notifications"],[Settings,"Settings","/dashboard/settings"]];
export function DashboardSidebar({ open, onClose }) { return <><button className={`dashboard-scrim ${open ? "is-open" : ""}`} onClick={onClose} aria-label="Close dashboard menu"/><aside className={`dashboard-sidebar ${open ? "is-open" : ""}`}><div className="dashboard-sidebar-brand"><Link to="/landingpage"><img src="/assets/sca_logo.png" alt="Short Circuit Arena"/></Link><button type="button" onClick={onClose} aria-label="Close dashboard menu"><X/></button></div><nav aria-label="Player dashboard">{dashboardNav.map(([Icon,label,path]) => <NavLink key={label} to={path} end={path === "/dashboard"} onClick={onClose} className={({isActive}) => isActive ? "is-active" : undefined}><Icon/><span>{label}</span></NavLink>)}</nav><Link className="dashboard-explore" to="/landingpage"><Swords/>Explore competitions</Link></aside></>; }
export function DashboardHeader({ title, user, onMenu }) { return <header className="dashboard-header"><button type="button" onClick={onMenu} aria-label="Open dashboard menu"><Menu/></button><div><p>Player dashboard</p><h1>{title}</h1></div><Link to="/dashboard/profile" className="dashboard-user"><span>{(user?.name || "P").slice(0,1).toUpperCase()}</span><div><strong>{user?.name || "Player"}</strong><small>View profile</small></div></Link></header>; }
export function StatusBadge({ children, tone="neutral" }) { return <span className={`dashboard-status status-${tone}`}>{children}</span>; }
export function EmptyState({ icon:Icon=Gamepad2, title, copy, action, to }) { return <div className="dashboard-empty"><Icon/><h3>{title}</h3><p>{copy}</p>{action && <Link className="button button-small" to={to}>{action}<ChevronRight/></Link>}</div>; }
export function PlayerSummary({ user }) { const name=user?.name || "Player"; const ign=user?.ign?.trim() || "IGN not set"; return <section className="player-summary"><div className="player-avatar">{ign === "IGN not set" ? name.slice(0,1).toUpperCase() : ign.slice(0,1).toUpperCase()}</div><div className="player-summary-copy"><div><StatusBadge tone="neutral">Unverified</StatusBadge><StatusBadge tone="accent">New player</StatusBadge></div><h2>{ign}</h2><p>{ign === "IGN not set" ? "Add your gamer tag to complete your profile" : `@${ign.replace(/\s+/g,"_").toLowerCase()}`}</p><dl><div><dt>Country</dt><dd>Not set</dd></div><div><dt>Games played</dt><dd>None added</dd></div><div><dt>Current team</dt><dd>No team</dd></div></dl></div><Link className="button button-secondary button-small" to="/dashboard/profile">Edit Profile</Link></section>; }
export function PlayerStats() { return <div className="player-stats">{[["0","Tournaments played"],["0","Tournament wins"],["0","Matches played"],["0%","Win rate"]].map(([value,label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div>; }
export function SectionTitle({ title, copy, action, to }) { return <div className="dashboard-section-title"><div><h2>{title}</h2>{copy && <p>{copy}</p>}</div>{action && <Link className="text-link" to={to}>{action}<ChevronRight/></Link>}</div>; }
export function CompetitionCard({ competition }) { return <article className="dashboard-competition"><img src={competition.image} alt=""/><div><StatusBadge tone="accent">{competition.status}</StatusBadge><h3>{competition.name}</h3><p>{competition.game}</p><dl><div><dt>Stage</dt><dd>{competition.stage}</dd></div><div><dt>Next match</dt><dd>{competition.next}</dd></div></dl><Link className="text-link" to={competition.to}>View Competition<ChevronRight/></Link></div></article>; }
export function AchievementBadge({ name, earned=false }) { if (!earned) return null; return <span className="achievement-badge"><Trophy/>{name}</span>; }
