import { ArrowLeft, Gamepad2, MapPin, Shield, Trophy, Users } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { getPlayerProfile } from "@/data/playerProfiles";
import "@/components/DashboardLayout/dashboard.css";

export default function PublicPlayerPage() {
  const {username}=useParams(); const navigate=useNavigate(); const player=getPlayerProfile(username); const teamSlug=player.team.toLowerCase().replace(/[^a-z0-9]+/g,"-");
  return <div className="public-player-page"><Navbar/><main><header className="public-player-header"><div className="dashboard-main"><button className="public-player-back" type="button" onClick={()=>window.history.state?.idx>0?navigate(-1):navigate("/landingpage")}><ArrowLeft/>Back to previous page</button><div className="public-player-hero"><div className="public-avatar">{player.image?<img src={player.image} alt={`Portrait of ${player.name}`}/>:player.ign.slice(0,1).toUpperCase()}</div><div><p className="eyebrow">SCA player profile</p><h1>{player.ign}</h1><p>{player.name}</p><div className="public-player-meta"><span><Shield/>{player.role}</span><span><Users/>{player.team}</span><span><Gamepad2/>{player.game}</span><span><MapPin/>{player.country}</span></div></div></div></div></header><div className="dashboard-main public-player-content"><section className="dashboard-panel public-player-about"><p className="eyebrow">Player overview</p><h2>About {player.ign}</h2><p>{player.bio}</p></section><section className="player-stats"><article><Trophy/><span>Tournaments</span><strong>4</strong></article><article><Shield/><span>Wins</span><strong>1</strong></article><article><Gamepad2/><span>Matches</span><strong>12</strong></article><article><Users/><span>Team</span><strong>{player.team==="No team"?"—":player.team}</strong></article></section><section className="dashboard-panel"><h2>Recent competition</h2><div className="public-competition-row"><div><span>Path of Legends</span><strong>Season 3</strong></div><small>Active</small></div></section>{player.team!=="No team"&&<section className="dashboard-panel public-team-cta"><div><p className="eyebrow">Current team</p><h2>{player.team}</h2></div><Link className="button button-secondary" to={`/teams/${teamSlug}`}>View team</Link></section>}</div></main><Footer/></div>;
}
